### ISSUE TITLE
schema_token and schema_host deprecated but required

### ISSUE THREAD

**Issue by annez** [rudderlabs/terraform-provider-rudderstack#8]
**Describe the issue**
The rudderstack documentation states that both `schema_host` and `schema_token` are deprecated and optional, but when running any terraform command the provider exits asking for both of these configuration settings.

**To Reproduce**

```
Existing provider set up:
provider "rudderstack" {
  # Set to control plane API host. Usually "https://api.rudderlabs.com/v2/".
  # If null, falls back on env variable RUDDERSTACK_HOST.
  host = "https://api.rudderlabs.com/v2/"

  # Set to access token for control plane API host.
  # The token can be generated at https://app.rudderlabs.com/profile/tokens. Example "1fasdasdsdas".
  # If null, falls back on env variable RUDDERSTACK_TOKEN.
  token = null

  schema_host  = null
  schema_token = null
}
```
1. With `RUDDERSTACK_TOKEN` run: `terraform plan`
2. See error
```
╷
│ Error: Unable to find schema token
│
│   with provider["registry.terraform.io/rudderlabs/rudderstack"],
│   on provider.tf line 21, in provider "rudderstack":
│   21: provider "rudderstack" {
│
│ Schema token cannot be an empty string
```

This happens with any combination of one or two of `schema_host` and `schema_token` to be null, which means the docs are not correct and these are both required settings in the latest version.

**Expected behavior**
Terraform plan should run correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/1567681/150770086-6dec99d8-568e-47f7-87f8-a776abdb4e23.png)

**Desktop (please complete the following information):**
- Provider version: 0.2.9 and 0.2.9
- Terraform version 1.1.0

**Comment by nishantsharma** [comment]
Bug fixed and release made.
